// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Bloodtype is the predicate function for bloodtype builders.
type Bloodtype func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// NameTitle is the predicate function for nametitle builders.
type NameTitle func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Status is the predicate function for status builders.
type Status func(*sql.Selector)
