// Code generated by entc, DO NOT EDIT.

package nametitle

const (
	// Label holds the string label denoting the nametitle type in the database.
	Label = "name_title"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"

	// Table holds the table name of the nametitle in the database.
	Table = "name_titles"
	// PatientTable is the table the holds the patient relation/edge.
	PatientTable = "patients"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "name_title_patient"
)

// Columns holds all SQL columns for nametitle fields.
var Columns = []string{
	FieldID,
	FieldName,
}
