// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Sujitnapa21/app/ent/nametitle"
	"github.com/Sujitnapa21/app/ent/patient"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// NameTitleCreate is the builder for creating a NameTitle entity.
type NameTitleCreate struct {
	config
	mutation *NameTitleMutation
	hooks    []Hook
}

// SetName sets the Name field.
func (ntc *NameTitleCreate) SetName(s string) *NameTitleCreate {
	ntc.mutation.SetName(s)
	return ntc
}

// AddPatientIDs adds the patient edge to Patient by ids.
func (ntc *NameTitleCreate) AddPatientIDs(ids ...int) *NameTitleCreate {
	ntc.mutation.AddPatientIDs(ids...)
	return ntc
}

// AddPatient adds the patient edges to Patient.
func (ntc *NameTitleCreate) AddPatient(p ...*Patient) *NameTitleCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ntc.AddPatientIDs(ids...)
}

// Mutation returns the NameTitleMutation object of the builder.
func (ntc *NameTitleCreate) Mutation() *NameTitleMutation {
	return ntc.mutation
}

// Save creates the NameTitle in the database.
func (ntc *NameTitleCreate) Save(ctx context.Context) (*NameTitle, error) {
	if _, ok := ntc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "Name", err: errors.New("ent: missing required field \"Name\"")}
	}
	var (
		err  error
		node *NameTitle
	)
	if len(ntc.hooks) == 0 {
		node, err = ntc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NameTitleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ntc.mutation = mutation
			node, err = ntc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ntc.hooks) - 1; i >= 0; i-- {
			mut = ntc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ntc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ntc *NameTitleCreate) SaveX(ctx context.Context) *NameTitle {
	v, err := ntc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ntc *NameTitleCreate) sqlSave(ctx context.Context) (*NameTitle, error) {
	nt, _spec := ntc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ntc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	nt.ID = int(id)
	return nt, nil
}

func (ntc *NameTitleCreate) createSpec() (*NameTitle, *sqlgraph.CreateSpec) {
	var (
		nt    = &NameTitle{config: ntc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: nametitle.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nametitle.FieldID,
			},
		}
	)
	if value, ok := ntc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: nametitle.FieldName,
		})
		nt.Name = value
	}
	if nodes := ntc.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nametitle.PatientTable,
			Columns: []string{nametitle.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return nt, _spec
}
