// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/Sujitnapa21/app/ent/nametitle"
	"github.com/Sujitnapa21/app/ent/patient"
	"github.com/Sujitnapa21/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// NameTitleQuery is the builder for querying NameTitle entities.
type NameTitleQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.NameTitle
	// eager-loading edges.
	withPatient *PatientQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (ntq *NameTitleQuery) Where(ps ...predicate.NameTitle) *NameTitleQuery {
	ntq.predicates = append(ntq.predicates, ps...)
	return ntq
}

// Limit adds a limit step to the query.
func (ntq *NameTitleQuery) Limit(limit int) *NameTitleQuery {
	ntq.limit = &limit
	return ntq
}

// Offset adds an offset step to the query.
func (ntq *NameTitleQuery) Offset(offset int) *NameTitleQuery {
	ntq.offset = &offset
	return ntq
}

// Order adds an order step to the query.
func (ntq *NameTitleQuery) Order(o ...OrderFunc) *NameTitleQuery {
	ntq.order = append(ntq.order, o...)
	return ntq
}

// QueryPatient chains the current query on the patient edge.
func (ntq *NameTitleQuery) QueryPatient() *PatientQuery {
	query := &PatientQuery{config: ntq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ntq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(nametitle.Table, nametitle.FieldID, ntq.sqlQuery()),
			sqlgraph.To(patient.Table, patient.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, nametitle.PatientTable, nametitle.PatientColumn),
		)
		fromU = sqlgraph.SetNeighbors(ntq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NameTitle entity in the query. Returns *NotFoundError when no nametitle was found.
func (ntq *NameTitleQuery) First(ctx context.Context) (*NameTitle, error) {
	nts, err := ntq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nts) == 0 {
		return nil, &NotFoundError{nametitle.Label}
	}
	return nts[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ntq *NameTitleQuery) FirstX(ctx context.Context) *NameTitle {
	nt, err := ntq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return nt
}

// FirstID returns the first NameTitle id in the query. Returns *NotFoundError when no id was found.
func (ntq *NameTitleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ntq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nametitle.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (ntq *NameTitleQuery) FirstXID(ctx context.Context) int {
	id, err := ntq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only NameTitle entity in the query, returns an error if not exactly one entity was returned.
func (ntq *NameTitleQuery) Only(ctx context.Context) (*NameTitle, error) {
	nts, err := ntq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nts) {
	case 1:
		return nts[0], nil
	case 0:
		return nil, &NotFoundError{nametitle.Label}
	default:
		return nil, &NotSingularError{nametitle.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ntq *NameTitleQuery) OnlyX(ctx context.Context) *NameTitle {
	nt, err := ntq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return nt
}

// OnlyID returns the only NameTitle id in the query, returns an error if not exactly one id was returned.
func (ntq *NameTitleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ntq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nametitle.Label}
	default:
		err = &NotSingularError{nametitle.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ntq *NameTitleQuery) OnlyIDX(ctx context.Context) int {
	id, err := ntq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NameTitles.
func (ntq *NameTitleQuery) All(ctx context.Context) ([]*NameTitle, error) {
	if err := ntq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ntq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ntq *NameTitleQuery) AllX(ctx context.Context) []*NameTitle {
	nts, err := ntq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nts
}

// IDs executes the query and returns a list of NameTitle ids.
func (ntq *NameTitleQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ntq.Select(nametitle.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ntq *NameTitleQuery) IDsX(ctx context.Context) []int {
	ids, err := ntq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ntq *NameTitleQuery) Count(ctx context.Context) (int, error) {
	if err := ntq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ntq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ntq *NameTitleQuery) CountX(ctx context.Context) int {
	count, err := ntq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ntq *NameTitleQuery) Exist(ctx context.Context) (bool, error) {
	if err := ntq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ntq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ntq *NameTitleQuery) ExistX(ctx context.Context) bool {
	exist, err := ntq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ntq *NameTitleQuery) Clone() *NameTitleQuery {
	return &NameTitleQuery{
		config:     ntq.config,
		limit:      ntq.limit,
		offset:     ntq.offset,
		order:      append([]OrderFunc{}, ntq.order...),
		unique:     append([]string{}, ntq.unique...),
		predicates: append([]predicate.NameTitle{}, ntq.predicates...),
		// clone intermediate query.
		sql:  ntq.sql.Clone(),
		path: ntq.path,
	}
}

//  WithPatient tells the query-builder to eager-loads the nodes that are connected to
// the "patient" edge. The optional arguments used to configure the query builder of the edge.
func (ntq *NameTitleQuery) WithPatient(opts ...func(*PatientQuery)) *NameTitleQuery {
	query := &PatientQuery{config: ntq.config}
	for _, opt := range opts {
		opt(query)
	}
	ntq.withPatient = query
	return ntq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NameTitle.Query().
//		GroupBy(nametitle.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ntq *NameTitleQuery) GroupBy(field string, fields ...string) *NameTitleGroupBy {
	group := &NameTitleGroupBy{config: ntq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ntq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ntq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//	}
//
//	client.NameTitle.Query().
//		Select(nametitle.FieldName).
//		Scan(ctx, &v)
//
func (ntq *NameTitleQuery) Select(field string, fields ...string) *NameTitleSelect {
	selector := &NameTitleSelect{config: ntq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ntq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ntq.sqlQuery(), nil
	}
	return selector
}

func (ntq *NameTitleQuery) prepareQuery(ctx context.Context) error {
	if ntq.path != nil {
		prev, err := ntq.path(ctx)
		if err != nil {
			return err
		}
		ntq.sql = prev
	}
	return nil
}

func (ntq *NameTitleQuery) sqlAll(ctx context.Context) ([]*NameTitle, error) {
	var (
		nodes       = []*NameTitle{}
		_spec       = ntq.querySpec()
		loadedTypes = [1]bool{
			ntq.withPatient != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &NameTitle{config: ntq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, ntq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ntq.withPatient; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*NameTitle)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Patient(func(s *sql.Selector) {
			s.Where(sql.InValues(nametitle.PatientColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.name_title_patient
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "name_title_patient" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "name_title_patient" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Patient = append(node.Edges.Patient, n)
		}
	}

	return nodes, nil
}

func (ntq *NameTitleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ntq.querySpec()
	return sqlgraph.CountNodes(ctx, ntq.driver, _spec)
}

func (ntq *NameTitleQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ntq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (ntq *NameTitleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   nametitle.Table,
			Columns: nametitle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nametitle.FieldID,
			},
		},
		From:   ntq.sql,
		Unique: true,
	}
	if ps := ntq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ntq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ntq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ntq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ntq *NameTitleQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(ntq.driver.Dialect())
	t1 := builder.Table(nametitle.Table)
	selector := builder.Select(t1.Columns(nametitle.Columns...)...).From(t1)
	if ntq.sql != nil {
		selector = ntq.sql
		selector.Select(selector.Columns(nametitle.Columns...)...)
	}
	for _, p := range ntq.predicates {
		p(selector)
	}
	for _, p := range ntq.order {
		p(selector)
	}
	if offset := ntq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ntq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NameTitleGroupBy is the builder for group-by NameTitle entities.
type NameTitleGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ntgb *NameTitleGroupBy) Aggregate(fns ...AggregateFunc) *NameTitleGroupBy {
	ntgb.fns = append(ntgb.fns, fns...)
	return ntgb
}

// Scan applies the group-by query and scan the result into the given value.
func (ntgb *NameTitleGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ntgb.path(ctx)
	if err != nil {
		return err
	}
	ntgb.sql = query
	return ntgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ntgb *NameTitleGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ntgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (ntgb *NameTitleGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ntgb.fields) > 1 {
		return nil, errors.New("ent: NameTitleGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ntgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ntgb *NameTitleGroupBy) StringsX(ctx context.Context) []string {
	v, err := ntgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (ntgb *NameTitleGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ntgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nametitle.Label}
	default:
		err = fmt.Errorf("ent: NameTitleGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ntgb *NameTitleGroupBy) StringX(ctx context.Context) string {
	v, err := ntgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (ntgb *NameTitleGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ntgb.fields) > 1 {
		return nil, errors.New("ent: NameTitleGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ntgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ntgb *NameTitleGroupBy) IntsX(ctx context.Context) []int {
	v, err := ntgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (ntgb *NameTitleGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ntgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nametitle.Label}
	default:
		err = fmt.Errorf("ent: NameTitleGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ntgb *NameTitleGroupBy) IntX(ctx context.Context) int {
	v, err := ntgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (ntgb *NameTitleGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ntgb.fields) > 1 {
		return nil, errors.New("ent: NameTitleGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ntgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ntgb *NameTitleGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ntgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (ntgb *NameTitleGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ntgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nametitle.Label}
	default:
		err = fmt.Errorf("ent: NameTitleGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ntgb *NameTitleGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ntgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (ntgb *NameTitleGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ntgb.fields) > 1 {
		return nil, errors.New("ent: NameTitleGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ntgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ntgb *NameTitleGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ntgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (ntgb *NameTitleGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ntgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nametitle.Label}
	default:
		err = fmt.Errorf("ent: NameTitleGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ntgb *NameTitleGroupBy) BoolX(ctx context.Context) bool {
	v, err := ntgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ntgb *NameTitleGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ntgb.sqlQuery().Query()
	if err := ntgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ntgb *NameTitleGroupBy) sqlQuery() *sql.Selector {
	selector := ntgb.sql
	columns := make([]string, 0, len(ntgb.fields)+len(ntgb.fns))
	columns = append(columns, ntgb.fields...)
	for _, fn := range ntgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(ntgb.fields...)
}

// NameTitleSelect is the builder for select fields of NameTitle entities.
type NameTitleSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (nts *NameTitleSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := nts.path(ctx)
	if err != nil {
		return err
	}
	nts.sql = query
	return nts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (nts *NameTitleSelect) ScanX(ctx context.Context, v interface{}) {
	if err := nts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (nts *NameTitleSelect) Strings(ctx context.Context) ([]string, error) {
	if len(nts.fields) > 1 {
		return nil, errors.New("ent: NameTitleSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := nts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (nts *NameTitleSelect) StringsX(ctx context.Context) []string {
	v, err := nts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (nts *NameTitleSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = nts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nametitle.Label}
	default:
		err = fmt.Errorf("ent: NameTitleSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (nts *NameTitleSelect) StringX(ctx context.Context) string {
	v, err := nts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (nts *NameTitleSelect) Ints(ctx context.Context) ([]int, error) {
	if len(nts.fields) > 1 {
		return nil, errors.New("ent: NameTitleSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := nts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (nts *NameTitleSelect) IntsX(ctx context.Context) []int {
	v, err := nts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (nts *NameTitleSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = nts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nametitle.Label}
	default:
		err = fmt.Errorf("ent: NameTitleSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (nts *NameTitleSelect) IntX(ctx context.Context) int {
	v, err := nts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (nts *NameTitleSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(nts.fields) > 1 {
		return nil, errors.New("ent: NameTitleSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := nts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (nts *NameTitleSelect) Float64sX(ctx context.Context) []float64 {
	v, err := nts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (nts *NameTitleSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = nts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nametitle.Label}
	default:
		err = fmt.Errorf("ent: NameTitleSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (nts *NameTitleSelect) Float64X(ctx context.Context) float64 {
	v, err := nts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (nts *NameTitleSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(nts.fields) > 1 {
		return nil, errors.New("ent: NameTitleSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := nts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (nts *NameTitleSelect) BoolsX(ctx context.Context) []bool {
	v, err := nts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (nts *NameTitleSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = nts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{nametitle.Label}
	default:
		err = fmt.Errorf("ent: NameTitleSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (nts *NameTitleSelect) BoolX(ctx context.Context) bool {
	v, err := nts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nts *NameTitleSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := nts.sqlQuery().Query()
	if err := nts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (nts *NameTitleSelect) sqlQuery() sql.Querier {
	selector := nts.sql
	selector.Select(selector.Columns(nts.fields...)...)
	return selector
}
