/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntNameTitleEdges,
    EntNameTitleEdgesFromJSON,
    EntNameTitleEdgesFromJSONTyped,
    EntNameTitleEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntNameTitle
 */
export interface EntNameTitle {
    /**
     * Name holds the value of the "Name" field.
     * @type {string}
     * @memberof EntNameTitle
     */
    name?: string;
    /**
     * 
     * @type {EntNameTitleEdges}
     * @memberof EntNameTitle
     */
    edges?: EntNameTitleEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntNameTitle
     */
    id?: number;
}

export function EntNameTitleFromJSON(json: any): EntNameTitle {
    return EntNameTitleFromJSONTyped(json, false);
}

export function EntNameTitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntNameTitle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'edges': !exists(json, 'edges') ? undefined : EntNameTitleEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntNameTitleToJSON(value?: EntNameTitle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'edges': EntNameTitleEdgesToJSON(value.edges),
        'id': value.id,
    };
}


